config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
 # patch “/bookings/:id/accept”, to: bookings#accept as: ‘accept’'
  #patch “/bookings/:id/decline”, to: bookings#decline, as: ‘decline’'
  root to: 'pages#home'
  get 'map', to: 'bikes#map'
  resources :bikes
  resources :bikes do
    resources :bookings, only:[:create,:new,:index,:show,:confirm ,:reject]
  end

  resources :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"
    has_one_attached  :photo
  #  belongs_to :district, foreign_key: "district_id"  >> DO NOT ENABLE THIS LINE IT WILL BREAK THINGS 
    geocoded_by :address
    after_validation :geocode# if: :will_save_change_to_address? HOTFX
    include PgSearch::Model
    pg_search_scope :search_by_title_and_description,
      against: [ :title, :description ],
      using: {
        tsearch: { prefix: true }
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :bike, foreign_key: "bike_id"
    belongs_to :user, foreign_key: "user_id"
end

app/models/district.rb
class District < ApplicationRecord
  has_many :bikes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    include Pundit

    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

    CATEGORIES = ["E-Bike","Mountain Bike"]
    DISTRICTS = ["Kreuzberg","Schöneberg"]
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:about,:password,:username,:photo])
  end
  
      private

    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    skip_before_action :authenticate_user!, only: [ :index ]


    def map
        @bikes = Bike.geocoded # returns flats with coordinates
        p @bikes

        @markers = @bikes.map do |bike|
          {
            lat: bike.latitude,
            lng: bike.longitude
          }
          authorize @bikes

      end
    end

    def new
        @user = User.find(current_user.id)
        @bike = Bike.new
        @categories = ["eBike", "City Bike","Mountain Bike","Fixed Gear","Road Bike","Trecking Bike","Unicycle"]
        @districts = District.all
        authorize @bike
    end

    def index
        @bikes = policy_scope(Bike).order(created_at: :desc)
        @bikes = @bikes.search_by_title_and_description(params[:query]) if params[:query].present?
        @bikes = Bike.where('category ILIKE ?', "%#{params[:category]}%") if params[:category].present?
      if params[:district].present?
        @district = District.find_by_name(params[:district])
        @bikes = Bike.where(district_id: @district)
      end
    end

    def edit
        @bike = Bike.find(params[:id])
        @user = User.find(current_user.id)
        @categories = ["eBike", "City Bike","Mountain Bike","Fixed Gear","Road Bike","Trecking Bike","Unicycle"]
        @districts = District.all
        authorize @bike
    end

    def update
        @bike = Bike.find(params[:id])
        authorize @bike
        if @bike.update(bike_params)
          redirect_to @bike, notice: 'Bike was successfully updated.'
        else
          render :edit
        end
    end

    def create
        @bike = Bike.new(bike_params)
        @user = User.find(current_user.id)
        @bike.user = @user
        authorize @bike
        if @bike.save
            redirect_to @bike, notice: 'Bike was added'
        else
            render :new, notice: 'Bike was not added'
        end

    end

    def show
        @bike = Bike.find(params[:id])
        @bookings = Booking.new
        authorize @bike

    end

    def destroy
        @bike = Bike.find(params[:id])
        @bike.destroy
        authorize @bike
        redirect_to bikes_path
    end


    private

    def bike_params
        params.require(:bike).permit(:title, :photo, :description, :district_id,:category)
    end
end

app/controllers/bookings_controller.rb
# frozen_string_literal: true

class BookingsController < ApplicationController
  def new
    @Bike = Bike.find(:id)
    @booking = Booking.new
    authorize @booking
    @booking.bike = @Bike
  end

  def create
    @booking = Booking.new(bookings_params)
    @bike = Bike.find(params[:bike_id])
    @user = User.find(current_user.id)
    @booking.bike = @bike
    @booking.user = @user
    @booking.confirmation_status = 'Pending'
    authorize @booking
    if @booking.save
      redirect_to bike_path(@bike), notice: 'Booking was requested.'
    else
      redirect_to bike_path(@bike), notice: 'Booking request has failed.'

    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(bookings_params)
      redirect_to bookings_path
    else
      render :edit
    end
    end

  def show
    @user = User.find(current_user.id)
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def index
    @user = User.find(current_user.id)
    @my_booking = policy_scope(Booking).where(user_id: @user.id)
    ## leaving this out because it breaks stuff
    @booking = policy_scope(Booking).joins(:bike).where("bikes.user_id = #{@user.id}")
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
    redirect_back(fallback_location: bookings_path)
  end

  def confirm
    @booking = Booking.find(params[:id])
    @booking.confirmation_status = 'Confirmed'
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.confirmation_status = 'Confirmed'
  end

  private

  def bookings_params
    params.permit(:starting_date, :end_date, :id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
    @bikes = Bike.all
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @bikes = Bike.where(user_id: @user.id)
    authorize @user
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/edit.html.erb
<br>
<br>
<div class="container-sm">
  <br>
  <h1> Edit this Bike </h1>
  <%= simple_form_for @bike do |f| %>
    <%= f.input :title, label: "Title"%>
    <%= f.input :description, size: 200, label: "Description:"%>
    <%= f.input :district_id, label: "District", collection: @districts %>
    <%= f.input :category, label: "Category:", collection: @categories%>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, "Edit your Bike now", class: "btn btn-danger mb-2"%>
  <%end%>
  <%= link_to  "Delete", bike_path ,method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure you want to delete' }%>
</div>
<br>
<br>
<br>

app/views/bikes/index.html.erb
<div class="container">
  <br>
  <h1 class="text-center">Fluffy bikes available <%= image_tag "giphy.gif", style: 'height:50px;width:50px;' %></h1>
<br>

 <div class="container pt-3 mb-3">
    <div class="row justify-content-center">
       <div class="col-12 col-md-6 col-lg-4">
  <%= form_tag bikes_path, method: :get, id: "form_adj" do %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a bike"
      %>
  </div>

      <div class="search-form-control form-group">
      <% district = params[:district].present? ? params[:district] : "Filter by Pickup Location" %>
      <%= select_tag :district, options_for_select(["Charlottenburg-Wilmersdorf", "Friedrichshain-Kreuzberg",
            "Lichtenberg", "Marzahn-Hellersdorf", "Mitte", "Pankow", "Reinickendorf", "Spandau","Steglitz-Zehlendorf", "Tempelhof-Schöneberg",
            "Treptow-Köpenick"], district),
            class: "form-control",
            :include_blank => "Filter by Pickup Location"
          %>
      </div>

      <div class="search-form-control form-group">
      <%= select_tag :category, options_for_select(["eBike", "City Bike","Mountain Bike","Fixed Gear","Road Bike","Trecking Bike","Unicycle"]),
        class: "form-control",
        :include_blank => "Filter by Bike Category"
      %>
      </div>

      <%= submit_tag "Search", class: "btn-danger mt-3 mx-auto d-block" %>

  <% end %>

  </div>
</div>
</div>

  <br>
<hr>
  <div class="card-wrapper">
    <% @bikes.each do |bike| %>
      <div class="card">
          <% if bike.photo.attached? %>
            <%= cl_image_tag bike.photo.key ,class: "card-img-top"%>
          <% else %>
            <%= image_tag "bike_placeholder_300x300.png", class: "card-img-top" %>
          <% end %>
          <div class="username text-center pt-3"> <%= bike.user.username %> </div>
        <div class="card-body">
          <h4 class="card-title"><strong> <%= bike.title %></strong></h4>
          <p class="card-text"><%=bike.description%></p>
            <% if policy(bike).edit? %>
            <%= link_to "Edit my Bike", edit_bike_path(bike), class: "btn btn-outline-danger align-self-end"%>
            <% else %>
            <%= link_to "Details", bike_path(bike), class: "button btn btn-danger" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/bikes/map.html.erb
<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>

app/views/bikes/new.html.erb
<br>
<br>
<div class="container-sm">
  <br>
  <h1>Add your Bike</h1>
  <%= simple_form_for @bike do |f| %>
    <%= f.input :title, label: "Title:"%>
    <%= f.input :description, size: 200, label: "Description:"%>
    <%= f.input :district_id, label: "District:", collection: @districts%>
    <%= f.input :category, label: "Category:", collection: @categories%>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, "Add your Bike now", class: "btn btn-danger"%>
  <%end%>
</div>
<br>
<br>
<br>

app/views/bikes/show.html.erb
<% if @bike.photo.attached? %>
  <%= cl_image_tag @bike.photo.key, class: "img-bike-show" %>
<% else %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1569943228307-a66beab7cd96?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1019&q=80);">
  </div>
<% end %>
<br>
<br>
<div class="container shadow-sm p-3 mb-5 bg-white rounded">
  <div class="d-flex flex-row">
    <div class="col-6">
    <h1><%= @bike.title%></h1>
    <br>
    <div class="avatar-bike">
      <% if @bike.user.photo.attached? %>
          <%= cl_image_tag @bike.user.photo.key, id: "avatar-large"  %>
        <% else %>
          <%= image_tag "bike_placeholder_300x300.png", id: "avatar-large" %>
        <% end %>
    </div>
    <%if @bike.district_id.present?%>
      <p> <i class="fas fa-map-marker-alt"></i> <strong>Pickup Location:</strong> <%= District.find(@bike.district_id).name %>
    <%end%>
    <p><i class="fas fa-bicycle"></i> <strong>Category:</strong><%= @bike.category %></p>
    <p><%= @bike.description %></p>
    <% if policy(@bike).edit? %>
      <%= link_to "Edit your Bike", edit_bike_path(@bike) %>
    <% end %>
  </div>
  <br>
  <br>
  <div class="col-6">
    <div class="booking">
      <h1> Book this Bike! </h1>
        <%= simple_form_for [@bike, @bookings] do |f| %>
          <%= f.input :starting_date, label: "From When"%>
          <%= f.input :end_date, label: "Until When"%>
          <%= f.submit 'Request Booking', class: 'btn btn-danger mx-auto d-block mt-2' %>
        <%end%>
    </div>
  </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <br>

  <ul class="list-inline tabs-underlined justify-content-center">
    <li class="tab-underlined tablinks" onclick="openCity(event, 'Mybookings')" id="defaultOpen">My Bookings</li>
    <li class="tab-underlined tablinks" onclick="openCity(event, 'PendingRequests')">Pending Bike Requests</li>
  </ul>
<div id="Mybookings" class="tabcontent">
    <% @my_booking.each do |booking| %>
    <div class="card-product m-2">
    <% if booking.bike.photo.attached?%>
    <%= cl_image_tag booking.bike.photo.key %>
    <% end %>
    <div class="card-product-infos">
    <h2><%= link_to booking.bike.title, bike_path(booking.bike)%></h2>
    <p>From <%= p booking.starting_date%> until  <%= p booking.end_date%>, the request is currently <%= booking.confirmation_status %></p>
  </div>
</div>
    <%end%>
</div>

<div id="PendingRequests" class="tabcontent">
      <% @booking.each do |booking| %>
        <div class="card-product m-2">
          <% if booking.user.photo.attached?%>
            <%= cl_image_tag booking.user.photo.key %>
          <% end %>
          <div class="card-product-infos">
            <h2><%=booking.user.username%> would like to book your bike <%=booking.bike.title%> </h2>
            <p>From <%= p booking.starting_date%> until  <%= p booking.end_date%>, the request is currently <%= booking.confirmation_status %></p>
          </div>
              <%# if booking.confirmation_status == "Pending" ||  booking.confirmation_status == "pending" %>
                <%#= simple_form_for [booking] do |f| %>
                   <%#= f.input :confirmation_status, :collection => %w[Pending Confirmed Rejected] %>
                   <%#= f.submit 'Send', class: 'btn btn-success' %>
                <%# end %>
              <%# end %>
        </div>
      <% end %>
  </div>





<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}

document.getElementById("defaultOpen").click();

</script>

app/views/bookings/show.html.erb
<%=@booking%>
<%=@booking.confirmation_status%>


<div class="container pt-5">
    <h2>confirm or reject this booking</h2>
    <%= simple_form_for [@booking] do |f| %>
    <%= f.input :confirmation_status, :collection => %w[Pending Confirmed Rejected] %>
    <%= f.submit 'Send', class: 'btn btn-success' %>
    <% end %>
    <hr>
    <%= link_to  "Back", bookings_path, class: "btn btn-success"%>
</div>x

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FluffyBikes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div id="page-container">
      <div id="content-wrap">
    <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<br>
<div class="container">
  <h1>Bikes of the day</h1>
<hr>
  <div class="card-wrapper">
    <% @bikes.limit(3).each do |bike| %>
      <div class="card">
          <% if bike.photo.attached? %>
            <%= cl_image_tag bike.photo.key, class: "card-img-top"  %>
          <% else %>
            <%= image_tag "bike_placeholder_300x300.png", class: "card-img-top" %>
          <% end %>
          <div class="username text-center pt-3"> <%= bike.user.username %> </div>
          <div class="card-body">
            <h4 class="card-title"><strong> <%= bike.title %></strong></h4>
            <p class="card-text"><%=bike.description%></p>
           <%= link_to "Details", bike_path(bike), class: "btn btn-danger" %>
        </div>
      </div>
    <% end %>
  </div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1571068316344-75bc76f77890?ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80)";>
  <div class="container">
    <h1 class="mb-1">Fluffy Bikes!</h1>
    <p>For a fluffy experience</p>
    <%= link_to "Rent a bike", bikes_path, class: "btn btn-danger btn-lg" %>
    <%= link_to "Offer a bike", new_bike_path, class: "btn btn-danger btn-lg ml-3" %>
  </div>
    </form>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer"> <p class="text-center pt-4">Made with fluffiness <i class="fas fa-heart"></i></p></footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand ml-2" do %>
    <%= image_tag "bike_logo.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <div class="dropdown">
            <div class="dropdown-toggle" type="text" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </div>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "Profile", current_user, method: :get, class: "dropdown-item" %>
              <%= link_to "Offer a Bike", new_bike_path, method: :get, class: "dropdown-item" %>
              <%= link_to "Rent a bike", bikes_path, method: :get, class: "dropdown-item" %>
              <%= link_to "Bookings", bookings_path, method: :get, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-links" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "nav-links" %>
          </li>
        <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-3">
  <div class="d-flex flex-row">
        <div class="col-6">
            <div class="card p-3 mb-3">
              <h1 class="pl-3 text-center">About</h1>
              <div class="avatar-profile">
              <% if @user.photo.attached? %>
                <%= cl_image_tag @user.photo.key, id: "avatar-large"  %>
              <% else %>
                <%= image_tag "bike_placeholder_300x300.png", id: "avatar-large" %>
              <% end %>
             </div>
              <p class="pl-3"><strong><%= @user.username %></strong></p>
              <p class="pl-3"><small><%= @user.about %></small></p>
              <%= link_to "Edit", edit_user_registration_path, class: "btn btn-danger ml-3 mx-auto d-block" %>
            </div>
        </div>

        <div class="col-6">
          <h2 class="text-center">My bikes for rent:</h2>
          <div class="listings">
            <%@bikes.each do |bike| %>
              <div class="card mt-0">
                <% if bike.photo.attached? %>
                  <%= cl_image_tag bike.photo.key, class: "card-img-top"  %>
                <% else %>
                  <%= image_tag "bike_placeholder_300x300.png", class: "card-img-top" %>
                <% end %>
                <div class="card-body">
                  <h4 class="card-title"><strong> <%= bike.title %></strong></h4>
                     <%= link_to "Details", bike_path(bike), class: "btn btn-danger" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
  </div>
</div>